<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class MakeViewCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:view {path : The view path (e.g., general.auth.login or sectors.poultry.batches.index)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new Blade view file';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $path = $this->argument('path');
        $viewPath = $this->getViewPath($path);

        if (File::exists($viewPath)) {
            $this->error("View already exists: {$viewPath}");
            return 1;
        }

        $directory = dirname($viewPath);
        if (!File::isDirectory($directory)) {
            File::makeDirectory($directory, 0755, true);
            $this->info("Created directory: {$directory}");
        }

        $stub = $this->getStub();
        File::put($viewPath, $stub);

        $this->info("View created: {$viewPath}");
        return 0;
    }

    /**
     * Convert dot notation to file path.
     */
    protected function getViewPath(string $path): string
    {
        $path = str_replace('.', '/', $path);
        return resource_path("views/{$path}.blade.php");
    }

    /**
     * Get the default stub content.
     */
    protected function getStub(): string
    {
        return <<<'BLADE'
@extends('layouts.app')

@section('title', '{{ ucfirst(str_replace('.', ' ', $path)) }}')

@section('content')
<div class="container mx-auto px-4 py-8">
    <h1 class="text-2xl font-bold text-gray-900">{{ ucfirst(str_replace('.', ' ', $path)) }}</h1>
    <p class="mt-2 text-gray-600">View generated by make:view command.</p>
</div>
@endsection
BLADE;
    }
}